/**********************************
 * Autogenerated -- do not modify *
 **********************************/

/* Must be before the include guards */
#ifdef UA_ENABLE_AMALGAMATION
#include "open62541.h"
#else
#include <open62541/types.h>
#endif

#ifndef TYPES_GMS_GENERATED_H_
#define TYPES_GMS_GENERATED_H_

_UA_BEGIN_DECLS

/**
 * Every type is assigned an index in an array containing the type descriptions.
 * These descriptions are used during type handling (copying, deletion,
 * binary encoding, ...). */
#define UA_TYPES_GMS_COUNT 6
extern UA_EXPORT UA_DataType UA_TYPES_GMS[UA_TYPES_GMS_COUNT];

/* CartesianWorkspaceType */
typedef struct {
  UA_Double length;
  UA_Double width;
  UA_Double height;
} UA_CartesianWorkspaceType;

#define UA_TYPES_GMS_CARTESIANWORKSPACETYPE 0

/* CylindricalWorkspaceType */
typedef struct {
  UA_Double length;
  UA_Double radius;
} UA_CylindricalWorkspaceType;

#define UA_TYPES_GMS_CYLINDRICALWORKSPACETYPE 1

/* MeasurementReasonEnum */
typedef enum {
  UA_MEASUREMENTREASONENUM_CONTINUOUSMEASUREMENTS = 0,
  UA_MEASUREMENTREASONENUM_SPECIALMEASUREMENT = 1,
  UA_MEASUREMENTREASONENUM_AUDITMEASUREMENT = 2,
  UA_MEASUREMENTREASONENUM_MINMASTERING = 3,
  UA_MEASUREMENTREASONENUM_MEDMASTERING = 4,
  UA_MEASUREMENTREASONENUM_MAXMASTERING = 5,
  __UA_MEASUREMENTREASONENUM_FORCE32BIT = 0x7fffffff
} UA_MeasurementReasonEnum;

UA_STATIC_ASSERT(sizeof(UA_MeasurementReasonEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_GMS_MEASUREMENTREASONENUM 2

/* ToleranceLimitEnum */
typedef enum {
  UA_TOLERANCELIMITENUM_NOLIMIT = 0,
  UA_TOLERANCELIMITENUM_LIMITVALUE = 1,
  UA_TOLERANCELIMITENUM_NATURALLIMIT = 2,
  __UA_TOLERANCELIMITENUM_FORCE32BIT = 0x7fffffff
} UA_ToleranceLimitEnum;

UA_STATIC_ASSERT(sizeof(UA_ToleranceLimitEnum) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_GMS_TOLERANCELIMITENUM 3

/* ToolAlignmentState */
typedef enum {
  UA_TOOLALIGNMENTSTATE_FIXED = 0,
  UA_TOOLALIGNMENTSTATE_INDEXED = 1,
  UA_TOOLALIGNMENTSTATE_CONTINUOUS = 2,
  __UA_TOOLALIGNMENTSTATE_FORCE32BIT = 0x7fffffff
} UA_ToolAlignmentState;

UA_STATIC_ASSERT(sizeof(UA_ToolAlignmentState) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_GMS_TOOLALIGNMENTSTATE 4

/* ToolIsQualifiedStatus */
typedef enum {
  UA_TOOLISQUALIFIEDSTATUS_QUALIFIED = 0,
  UA_TOOLISQUALIFIEDSTATUS_IMPRECISE = 1,
  UA_TOOLISQUALIFIEDSTATUS_NOTQUALIFIED = 2,
  __UA_TOOLISQUALIFIEDSTATUS_FORCE32BIT = 0x7fffffff
} UA_ToolIsQualifiedStatus;

UA_STATIC_ASSERT(sizeof(UA_ToolIsQualifiedStatus) == sizeof(UA_Int32), enum_must_be_32bit);

#define UA_TYPES_GMS_TOOLISQUALIFIEDSTATUS 5

_UA_END_DECLS

#endif /* TYPES_GMS_GENERATED_H_ */
