/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#include "types_gms_generated.h"

/* CartesianWorkspaceType */
static UA_DataTypeMember CartesianWorkspaceType_members[3] = {
  {
    UA_TYPENAME("Length")          /* .memberName */
      & UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    0,                             /* .padding */
    false,                         /* .isArray */
    false                          /* .isOptional */
  },
  {
    UA_TYPENAME("Width")                                                                                          /* .memberName */
      & UA_TYPES[UA_TYPES_DOUBLE],                                                                                /* .memberType */
    offsetof(UA_CartesianWorkspaceType, width) - offsetof(UA_CartesianWorkspaceType, length) - sizeof(UA_Double), /* .padding */
    false,                                                                                                        /* .isArray */
    false                                                                                                         /* .isOptional */
  },
  {
    UA_TYPENAME("Height")                                                                                         /* .memberName */
      & UA_TYPES[UA_TYPES_DOUBLE],                                                                                /* .memberType */
    offsetof(UA_CartesianWorkspaceType, height) - offsetof(UA_CartesianWorkspaceType, width) - sizeof(UA_Double), /* .padding */
    false,                                                                                                        /* .isArray */
    false                                                                                                         /* .isOptional */
  },
};

/* CylindricalWorkspaceType */
static UA_DataTypeMember CylindricalWorkspaceType_members[2] = {
  {
    UA_TYPENAME("Length")          /* .memberName */
      & UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    0,                             /* .padding */
    false,                         /* .isArray */
    false                          /* .isOptional */
  },
  {
    UA_TYPENAME("Radius")                                                                                              /* .memberName */
      & UA_TYPES[UA_TYPES_DOUBLE],                                                                                     /* .memberType */
    offsetof(UA_CylindricalWorkspaceType, radius) - offsetof(UA_CylindricalWorkspaceType, length) - sizeof(UA_Double), /* .padding */
    false,                                                                                                             /* .isArray */
    false                                                                                                              /* .isOptional */
  },
};

/* MeasurementReasonEnum */
#define MeasurementReasonEnum_members NULL

/* ToleranceLimitEnum */
#define ToleranceLimitEnum_members NULL

/* ToolAlignmentState */
#define ToolAlignmentState_members NULL

/* ToolIsQualifiedStatus */
#define ToolIsQualifiedStatus_members NULL
UA_DataType UA_TYPES_GMS[UA_TYPES_GMS_COUNT] = {
  /* CartesianWorkspaceType */
  {
    UA_TYPENAME("CartesianWorkspaceType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3007LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5007LU}}, /* .binaryEncodingId */
    sizeof(UA_CartesianWorkspaceType),    /* .memSize */
    UA_DATATYPEKIND_STRUCTURE,            /* .typeKind */
    true,                                 /* .pointerFree */
    false,                                /* .overlayable */
    3,                                    /* .membersSize */
    CartesianWorkspaceType_members        /* .members */
  },
  /* CylindricalWorkspaceType */
  {
    UA_TYPENAME("CylindricalWorkspaceType") /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3008LU}},   /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {5013LU}},   /* .binaryEncodingId */
    sizeof(UA_CylindricalWorkspaceType),    /* .memSize */
    UA_DATATYPEKIND_STRUCTURE,              /* .typeKind */
    true,                                   /* .pointerFree */
    false,                                  /* .overlayable */
    2,                                      /* .membersSize */
    CylindricalWorkspaceType_members        /* .members */
  },
  /* MeasurementReasonEnum */
  {
    UA_TYPENAME("MeasurementReasonEnum")  /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3009LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}},      /* .binaryEncodingId */
    sizeof(UA_MeasurementReasonEnum),     /* .memSize */
    UA_DATATYPEKIND_ENUM,                 /* .typeKind */
    true,                                 /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER,        /* .overlayable */
    0,                                    /* .membersSize */
    MeasurementReasonEnum_members         /* .members */
  },
  /* ToleranceLimitEnum */
  {
    UA_TYPENAME("ToleranceLimitEnum")     /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3010LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}},      /* .binaryEncodingId */
    sizeof(UA_ToleranceLimitEnum),        /* .memSize */
    UA_DATATYPEKIND_ENUM,                 /* .typeKind */
    true,                                 /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER,        /* .overlayable */
    0,                                    /* .membersSize */
    ToleranceLimitEnum_members            /* .members */
  },
  /* ToolAlignmentState */
  {
    UA_TYPENAME("ToolAlignmentState")     /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3004LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}},      /* .binaryEncodingId */
    sizeof(UA_ToolAlignmentState),        /* .memSize */
    UA_DATATYPEKIND_ENUM,                 /* .typeKind */
    true,                                 /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER,        /* .overlayable */
    0,                                    /* .membersSize */
    ToolAlignmentState_members            /* .members */
  },
  /* ToolIsQualifiedStatus */
  {
    UA_TYPENAME("ToolIsQualifiedStatus")  /* .typeName */
    {0, UA_NODEIDTYPE_NUMERIC, {3002LU}}, /* .typeId */
    {0, UA_NODEIDTYPE_NUMERIC, {0}},      /* .binaryEncodingId */
    sizeof(UA_ToolIsQualifiedStatus),     /* .memSize */
    UA_DATATYPEKIND_ENUM,                 /* .typeKind */
    true,                                 /* .pointerFree */
    UA_BINARY_OVERLAYABLE_INTEGER,        /* .overlayable */
    0,                                    /* .membersSize */
    ToolIsQualifiedStatus_members         /* .members */
  },
};
