/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#include <open62541/types.h>

#ifndef TYPES_IJT_GENERATED_GENERATED_H_
#define TYPES_IJT_GENERATED_GENERATED_H_

#include "types_machinery_result_generated.h"

_UA_BEGIN_DECLS

/**
 * Every type is assigned an index in an array containing the type descriptions.
 * These descriptions are used during type handling (copying, deletion,
 * binary encoding, ...). */
#define UA_TYPES_IJT_GENERATED_COUNT 22
extern UA_EXPORT UA_DataType UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_COUNT];

/* CalibrationDataType: This structure contains the Calibration information. It is used as an input argument in SetCalibration method.
Note: The input data sent in SetCalibration shall be updated in the respective parameters of the asset under Maintenance/Calibration. */
typedef struct {
  UA_DateTime lastCalibration;
  UA_String *calibrationPlace;
  UA_DateTime *nextCalibration;
  UA_Double *calibrationValue;
  UA_Double *sensorScale;
  UA_String *certificateUri;
  UA_EUInformation *engineeringUnits;
} UA_CalibrationDataType;

#define UA_TYPES_IJT_GENERATED_CALIBRATIONDATATYPE 0

UA_INLINABLE(void UA_CalibrationDataType_init(UA_CalibrationDataType *p), { memset(p, 0, sizeof(UA_CalibrationDataType)); })

UA_INLINABLE(UA_CalibrationDataType *UA_CalibrationDataType_new(void), {
  return (UA_CalibrationDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_CALIBRATIONDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_CalibrationDataType_copy(const UA_CalibrationDataType *src, UA_CalibrationDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_CALIBRATIONDATATYPE]);
})

UA_INLINABLE(void UA_CalibrationDataType_clear(UA_CalibrationDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_CALIBRATIONDATATYPE]);
})

UA_INLINABLE(void UA_CalibrationDataType_delete(UA_CalibrationDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_CALIBRATIONDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_CalibrationDataType_equal(const UA_CalibrationDataType *p1, const UA_CalibrationDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_CALIBRATIONDATATYPE]) == UA_ORDER_EQ);
})

/* DesignValueDataType: This structure provides the design value for a given physical quantity. It is used in JointDesignDataType. */
typedef struct {
  UA_Byte *physicalQuantity;
  UA_String *name;
  UA_Variant *designValue;
  UA_EUInformation *engineeringUnits;
} UA_DesignValueDataType;

#define UA_TYPES_IJT_GENERATED_DESIGNVALUEDATATYPE 1

UA_INLINABLE(void UA_DesignValueDataType_init(UA_DesignValueDataType *p), { memset(p, 0, sizeof(UA_DesignValueDataType)); })

UA_INLINABLE(UA_DesignValueDataType *UA_DesignValueDataType_new(void), {
  return (UA_DesignValueDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_DESIGNVALUEDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_DesignValueDataType_copy(const UA_DesignValueDataType *src, UA_DesignValueDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_DESIGNVALUEDATATYPE]);
})

UA_INLINABLE(void UA_DesignValueDataType_clear(UA_DesignValueDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_DESIGNVALUEDATATYPE]);
})

UA_INLINABLE(void UA_DesignValueDataType_delete(UA_DesignValueDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_DESIGNVALUEDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_DesignValueDataType_equal(const UA_DesignValueDataType *p1, const UA_DesignValueDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_DESIGNVALUEDATATYPE]) == UA_ORDER_EQ);
})

/* EntityDataType: This structure provides the identification data for a given entity in the system. */
typedef struct {
  UA_String *name;
  UA_String *description;
  UA_String entityId;
  UA_String *entityOriginId;
  UA_Boolean *isExternal;
  UA_Int16 entityType;
} UA_EntityDataType;

#define UA_TYPES_IJT_GENERATED_ENTITYDATATYPE 2

UA_INLINABLE(void UA_EntityDataType_init(UA_EntityDataType *p), { memset(p, 0, sizeof(UA_EntityDataType)); })

UA_INLINABLE(UA_EntityDataType *UA_EntityDataType_new(void), {
  return (UA_EntityDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ENTITYDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_EntityDataType_copy(const UA_EntityDataType *src, UA_EntityDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ENTITYDATATYPE]);
})

UA_INLINABLE(void UA_EntityDataType_clear(UA_EntityDataType *p), { UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ENTITYDATATYPE]); })

UA_INLINABLE(void UA_EntityDataType_delete(UA_EntityDataType *p), { UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ENTITYDATATYPE]); })

UA_INLINABLE(UA_Boolean UA_EntityDataType_equal(const UA_EntityDataType *p1, const UA_EntityDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ENTITYDATATYPE]) == UA_ORDER_EQ);
})

/* ErrorInformationDataType: This structure represents the errors occurred in the system which are outside the boundaries of the given program. */
typedef struct {
  UA_Byte errorType;
  UA_String *errorId;
  UA_String *legacyError;
  UA_LocalizedText *errorMessage;
} UA_ErrorInformationDataType;

#define UA_TYPES_IJT_GENERATED_ERRORINFORMATIONDATATYPE 3

UA_INLINABLE(void UA_ErrorInformationDataType_init(UA_ErrorInformationDataType *p), { memset(p, 0, sizeof(UA_ErrorInformationDataType)); })

UA_INLINABLE(UA_ErrorInformationDataType *UA_ErrorInformationDataType_new(void), {
  return (UA_ErrorInformationDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ERRORINFORMATIONDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_ErrorInformationDataType_copy(const UA_ErrorInformationDataType *src, UA_ErrorInformationDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ERRORINFORMATIONDATATYPE]);
})

UA_INLINABLE(void UA_ErrorInformationDataType_clear(UA_ErrorInformationDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ERRORINFORMATIONDATATYPE]);
})

UA_INLINABLE(void UA_ErrorInformationDataType_delete(UA_ErrorInformationDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ERRORINFORMATIONDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_ErrorInformationDataType_equal(const UA_ErrorInformationDataType *p1, const UA_ErrorInformationDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_ERRORINFORMATIONDATATYPE]) == UA_ORDER_EQ);
})

/* JoiningProcessDataType: This structure provides the base container for any joining process in a joining system.
Note: This specification defines the meta data of a JoiningProcess, and the actual content of the Joining Process is application specific. */
typedef struct {
  UA_ExtensionObject joiningProcessMetaData;
  size_t joiningProcessContentSize;
  UA_Variant *joiningProcessContent;
} UA_JoiningProcessDataType;

#define UA_TYPES_IJT_GENERATED_JOININGPROCESSDATATYPE 4

UA_INLINABLE(void UA_JoiningProcessDataType_init(UA_JoiningProcessDataType *p), { memset(p, 0, sizeof(UA_JoiningProcessDataType)); })

UA_INLINABLE(UA_JoiningProcessDataType *UA_JoiningProcessDataType_new(void), {
  return (UA_JoiningProcessDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JoiningProcessDataType_copy(const UA_JoiningProcessDataType *src, UA_JoiningProcessDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSDATATYPE]);
})

UA_INLINABLE(void UA_JoiningProcessDataType_clear(UA_JoiningProcessDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSDATATYPE]);
})

UA_INLINABLE(void UA_JoiningProcessDataType_delete(UA_JoiningProcessDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_JoiningProcessDataType_equal(const UA_JoiningProcessDataType *p1, const UA_JoiningProcessDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSDATATYPE]) == UA_ORDER_EQ);
})

/* JoiningProcessIdentificationDataType: This structure contains the identification information of a Joining Process. It is used in set of methods defined in
 * JoiningProcessManagementType. */
typedef struct {
  UA_String *joiningProcessId;
  UA_String *joiningProcessOriginId;
  UA_String *selectionName;
} UA_JoiningProcessIdentificationDataType;

#define UA_TYPES_IJT_GENERATED_JOININGPROCESSIDENTIFICATIONDATATYPE 5

UA_INLINABLE(void UA_JoiningProcessIdentificationDataType_init(UA_JoiningProcessIdentificationDataType *p), {
  memset(p, 0, sizeof(UA_JoiningProcessIdentificationDataType));
})

UA_INLINABLE(UA_JoiningProcessIdentificationDataType *UA_JoiningProcessIdentificationDataType_new(void), {
  return (UA_JoiningProcessIdentificationDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSIDENTIFICATIONDATATYPE]);
})

UA_INLINABLE(
  UA_StatusCode UA_JoiningProcessIdentificationDataType_copy(const UA_JoiningProcessIdentificationDataType *src, UA_JoiningProcessIdentificationDataType *dst),
  { return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSIDENTIFICATIONDATATYPE]); })

UA_INLINABLE(void UA_JoiningProcessIdentificationDataType_clear(UA_JoiningProcessIdentificationDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSIDENTIFICATIONDATATYPE]);
})

UA_INLINABLE(void UA_JoiningProcessIdentificationDataType_delete(UA_JoiningProcessIdentificationDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSIDENTIFICATIONDATATYPE]);
})

UA_INLINABLE(
  UA_Boolean UA_JoiningProcessIdentificationDataType_equal(
    const UA_JoiningProcessIdentificationDataType *p1, const UA_JoiningProcessIdentificationDataType *p2),
  { return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSIDENTIFICATIONDATATYPE]) == UA_ORDER_EQ); })

/* JoiningProcessMetaDataType: This structure provides the meta data which describes the joining process. */
typedef struct {
  UA_String joiningProcessId;
  UA_String *joiningProcessOriginId;
  UA_DateTime *creationTime;
  UA_DateTime *lastUpdatedTime;
  UA_String *name;
  UA_LocalizedText *description;
  UA_LocalizedText *joiningTechnology;
  UA_Int16 *classification;
  size_t associatedEntitiesSize;
  UA_EntityDataType *associatedEntities;
} UA_JoiningProcessMetaDataType;

#define UA_TYPES_IJT_GENERATED_JOININGPROCESSMETADATATYPE 6

UA_INLINABLE(void UA_JoiningProcessMetaDataType_init(UA_JoiningProcessMetaDataType *p), { memset(p, 0, sizeof(UA_JoiningProcessMetaDataType)); })

UA_INLINABLE(UA_JoiningProcessMetaDataType *UA_JoiningProcessMetaDataType_new(void), {
  return (UA_JoiningProcessMetaDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSMETADATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JoiningProcessMetaDataType_copy(const UA_JoiningProcessMetaDataType *src, UA_JoiningProcessMetaDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSMETADATATYPE]);
})

UA_INLINABLE(void UA_JoiningProcessMetaDataType_clear(UA_JoiningProcessMetaDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSMETADATATYPE]);
})

UA_INLINABLE(void UA_JoiningProcessMetaDataType_delete(UA_JoiningProcessMetaDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSMETADATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_JoiningProcessMetaDataType_equal(const UA_JoiningProcessMetaDataType *p1, const UA_JoiningProcessMetaDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGPROCESSMETADATATYPE]) == UA_ORDER_EQ);
})

/* JointComponentDataType: This structure is the base container for any joint component such as Bolt, Rivet, Gasket, Glue string, etc.
Note: The concrete definition of joint component is not defined in this version of the specification. */
typedef struct {
  UA_String jointComponentId;
  UA_String *name;
  UA_LocalizedText *description;
  UA_LocalizedText *manufacturer;
  UA_String *manufacturerUri;
  UA_Variant *jointComponentContent;
} UA_JointComponentDataType;

#define UA_TYPES_IJT_GENERATED_JOINTCOMPONENTDATATYPE 7

UA_INLINABLE(void UA_JointComponentDataType_init(UA_JointComponentDataType *p), { memset(p, 0, sizeof(UA_JointComponentDataType)); })

UA_INLINABLE(UA_JointComponentDataType *UA_JointComponentDataType_new(void), {
  return (UA_JointComponentDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTCOMPONENTDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JointComponentDataType_copy(const UA_JointComponentDataType *src, UA_JointComponentDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTCOMPONENTDATATYPE]);
})

UA_INLINABLE(void UA_JointComponentDataType_clear(UA_JointComponentDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTCOMPONENTDATATYPE]);
})

UA_INLINABLE(void UA_JointComponentDataType_delete(UA_JointComponentDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTCOMPONENTDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_JointComponentDataType_equal(const UA_JointComponentDataType *p1, const UA_JointComponentDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTCOMPONENTDATATYPE]) == UA_ORDER_EQ);
})

/* JointDataType: This structure provides the joint information. Joint is the physical outcome of the joining operation which determines the properties of the
 * point where multiple parts are assembled. */
typedef struct {
  UA_String jointId;
  UA_String *jointOriginId;
  UA_String *jointDesignId;
  UA_DateTime *creationTime;
  UA_DateTime *lastUpdatedTime;
  UA_String *name;
  UA_LocalizedText *description;
  UA_Int16 *classification;
  UA_LocalizedText *classificationDetails;
  UA_String *jointStatus;
  size_t associatedEntitiesSize;
  UA_EntityDataType *associatedEntities;
  UA_LocalizedText *joiningTechnology;
} UA_JointDataType;

#define UA_TYPES_IJT_GENERATED_JOINTDATATYPE 8

UA_INLINABLE(void UA_JointDataType_init(UA_JointDataType *p), { memset(p, 0, sizeof(UA_JointDataType)); })

UA_INLINABLE(UA_JointDataType *UA_JointDataType_new(void), {
  return (UA_JointDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JointDataType_copy(const UA_JointDataType *src, UA_JointDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDATATYPE]);
})

UA_INLINABLE(void UA_JointDataType_clear(UA_JointDataType *p), { UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDATATYPE]); })

UA_INLINABLE(void UA_JointDataType_delete(UA_JointDataType *p), { UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDATATYPE]); })

UA_INLINABLE(UA_Boolean UA_JointDataType_equal(const UA_JointDataType *p1, const UA_JointDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDATATYPE]) == UA_ORDER_EQ);
})

/* JointDesignDataType: This structure provides the design information of a given joint. */
typedef struct {
  UA_String jointDesignId;
  UA_String *name;
  UA_LocalizedText *description;
  size_t jointDesignContentSize;
  UA_DesignValueDataType *jointDesignContent;
  size_t jointComponentIdListSize;
  UA_String *jointComponentIdList;
} UA_JointDesignDataType;

#define UA_TYPES_IJT_GENERATED_JOINTDESIGNDATATYPE 9

UA_INLINABLE(void UA_JointDesignDataType_init(UA_JointDesignDataType *p), { memset(p, 0, sizeof(UA_JointDesignDataType)); })

UA_INLINABLE(UA_JointDesignDataType *UA_JointDesignDataType_new(void), {
  return (UA_JointDesignDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDESIGNDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JointDesignDataType_copy(const UA_JointDesignDataType *src, UA_JointDesignDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDESIGNDATATYPE]);
})

UA_INLINABLE(void UA_JointDesignDataType_clear(UA_JointDesignDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDESIGNDATATYPE]);
})

UA_INLINABLE(void UA_JointDesignDataType_delete(UA_JointDesignDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDESIGNDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_JointDesignDataType_equal(const UA_JointDesignDataType *p1, const UA_JointDesignDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOINTDESIGNDATATYPE]) == UA_ORDER_EQ);
})

/* KeyValueDataType: This structure is similar to 0:KeyValuePair which uses 0:TrimmedString instead of 0:QualifiedName. */
typedef struct {
  UA_String key;
  UA_Variant value;
} UA_KeyValueDataType;

#define UA_TYPES_IJT_GENERATED_KEYVALUEDATATYPE 10

UA_INLINABLE(void UA_KeyValueDataType_init(UA_KeyValueDataType *p), { memset(p, 0, sizeof(UA_KeyValueDataType)); })

UA_INLINABLE(UA_KeyValueDataType *UA_KeyValueDataType_new(void), {
  return (UA_KeyValueDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_KEYVALUEDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_KeyValueDataType_copy(const UA_KeyValueDataType *src, UA_KeyValueDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_KEYVALUEDATATYPE]);
})

UA_INLINABLE(void UA_KeyValueDataType_clear(UA_KeyValueDataType *p), { UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_KEYVALUEDATATYPE]); })

UA_INLINABLE(void UA_KeyValueDataType_delete(UA_KeyValueDataType *p), { UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_KEYVALUEDATATYPE]); })

UA_INLINABLE(UA_Boolean UA_KeyValueDataType_equal(const UA_KeyValueDataType *p1, const UA_KeyValueDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_KEYVALUEDATATYPE]) == UA_ORDER_EQ);
})

/* ReportedValueDataType: This structure provides the given value and corresponding limits for a given physical quantity (if applicable). */
typedef struct {
  UA_Byte *physicalQuantity;
  UA_String *name;
  UA_Variant currentValue;
  UA_Variant *previousValue;
  UA_Double *lowLimit;
  UA_Double *highLimit;
  UA_EUInformation *engineeringUnits;
} UA_ReportedValueDataType;

#define UA_TYPES_IJT_GENERATED_REPORTEDVALUEDATATYPE 11

UA_INLINABLE(void UA_ReportedValueDataType_init(UA_ReportedValueDataType *p), { memset(p, 0, sizeof(UA_ReportedValueDataType)); })

UA_INLINABLE(UA_ReportedValueDataType *UA_ReportedValueDataType_new(void), {
  return (UA_ReportedValueDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_REPORTEDVALUEDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_ReportedValueDataType_copy(const UA_ReportedValueDataType *src, UA_ReportedValueDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_REPORTEDVALUEDATATYPE]);
})

UA_INLINABLE(void UA_ReportedValueDataType_clear(UA_ReportedValueDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_REPORTEDVALUEDATATYPE]);
})

UA_INLINABLE(void UA_ReportedValueDataType_delete(UA_ReportedValueDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_REPORTEDVALUEDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_ReportedValueDataType_equal(const UA_ReportedValueDataType *p1, const UA_ReportedValueDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_REPORTEDVALUEDATATYPE]) == UA_ORDER_EQ);
})

/* ResultCounterDataType: This structure is used to provide various types of counters associated to a Result. These counters are related to a joining process
 * with sub-processes. */
typedef struct {
  UA_String *name;
  UA_UInt32 counterValue;
  UA_Int16 counterType;
} UA_ResultCounterDataType;

#define UA_TYPES_IJT_GENERATED_RESULTCOUNTERDATATYPE 12

UA_INLINABLE(void UA_ResultCounterDataType_init(UA_ResultCounterDataType *p), { memset(p, 0, sizeof(UA_ResultCounterDataType)); })

UA_INLINABLE(UA_ResultCounterDataType *UA_ResultCounterDataType_new(void), {
  return (UA_ResultCounterDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTCOUNTERDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_ResultCounterDataType_copy(const UA_ResultCounterDataType *src, UA_ResultCounterDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTCOUNTERDATATYPE]);
})

UA_INLINABLE(void UA_ResultCounterDataType_clear(UA_ResultCounterDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTCOUNTERDATATYPE]);
})

UA_INLINABLE(void UA_ResultCounterDataType_delete(UA_ResultCounterDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTCOUNTERDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_ResultCounterDataType_equal(const UA_ResultCounterDataType *p1, const UA_ResultCounterDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTCOUNTERDATATYPE]) == UA_ORDER_EQ);
})

/* JoiningResultMetaDataType: This structure is a subtype of ResultMetaDataType. It is used to define additional meta data of a Result in a joining system. */
typedef struct {
  UA_String resultId;
  UA_Boolean *hasTransferableDataOnFile;
  UA_Boolean *isPartial;
  UA_Boolean *isSimulated;
  UA_Int32 *resultState;
  UA_String *stepId;
  UA_String *partId;
  UA_String *externalRecipeId;
  UA_String *internalRecipeId;
  UA_String *productId;
  UA_String *externalConfigurationId;
  UA_String *internalConfigurationId;
  UA_String *jobId;
  UA_DateTime *creationTime;
  UA_ProcessingTimesDataType *processingTimes;
  size_t resultUriSize;
  UA_String *resultUri;
  UA_ResultEvaluationEnum *resultEvaluation;
  UA_Int64 *resultEvaluationCode;
  UA_LocalizedText *resultEvaluationDetails;
  size_t fileFormatSize;
  UA_String *fileFormat;
  UA_LocalizedText *joiningTechnology;
  UA_UInt64 *sequenceNumber;
  UA_String *name;
  UA_LocalizedText *description;
  UA_Byte *classification;
  UA_Byte *operationMode;
  UA_Byte *assemblyType;
  size_t associatedEntitiesSize;
  UA_EntityDataType *associatedEntities;
  size_t resultCountersSize;
  UA_ResultCounterDataType *resultCounters;
  UA_Byte *interventionType;
  UA_Boolean *isGeneratedOffline;
  size_t extendedMetaDataSize;
  UA_KeyValueDataType *extendedMetaData;
} UA_JoiningResultMetaDataType;

#define UA_TYPES_IJT_GENERATED_JOININGRESULTMETADATATYPE 13

UA_INLINABLE(void UA_JoiningResultMetaDataType_init(UA_JoiningResultMetaDataType *p), { memset(p, 0, sizeof(UA_JoiningResultMetaDataType)); })

UA_INLINABLE(UA_JoiningResultMetaDataType *UA_JoiningResultMetaDataType_new(void), {
  return (UA_JoiningResultMetaDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTMETADATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JoiningResultMetaDataType_copy(const UA_JoiningResultMetaDataType *src, UA_JoiningResultMetaDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTMETADATATYPE]);
})

UA_INLINABLE(void UA_JoiningResultMetaDataType_clear(UA_JoiningResultMetaDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTMETADATATYPE]);
})

UA_INLINABLE(void UA_JoiningResultMetaDataType_delete(UA_JoiningResultMetaDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTMETADATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_JoiningResultMetaDataType_equal(const UA_JoiningResultMetaDataType *p1, const UA_JoiningResultMetaDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTMETADATATYPE]) == UA_ORDER_EQ);
})

/* ResultValueDataType: It is used to report measurement values of the joining operation. Those are meant to characterize the quality of the process. It is used
 * in JoiningResultDataType and StepResultDataType. */
typedef struct {
  UA_Double measuredValue;
  UA_String *name;
  UA_ResultEvaluationEnum *resultEvaluation;
  UA_String *valueId;
  UA_Int16 *valueTag;
  UA_Int32 *tracePointIndex;
  UA_Double *tracePointTimeOffset;
  size_t parameterIdListSize;
  UA_String *parameterIdList;
  UA_Byte *violationType;
  UA_Byte *violationConsequence;
  UA_String *sensorId;
  UA_Double *lowLimit;
  UA_Double *highLimit;
  UA_Double *targetValue;
  UA_String *resultStep;
  UA_Byte *physicalQuantity;
  UA_EUInformation *engineeringUnits;
} UA_ResultValueDataType;

#define UA_TYPES_IJT_GENERATED_RESULTVALUEDATATYPE 14

UA_INLINABLE(void UA_ResultValueDataType_init(UA_ResultValueDataType *p), { memset(p, 0, sizeof(UA_ResultValueDataType)); })

UA_INLINABLE(UA_ResultValueDataType *UA_ResultValueDataType_new(void), {
  return (UA_ResultValueDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTVALUEDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_ResultValueDataType_copy(const UA_ResultValueDataType *src, UA_ResultValueDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTVALUEDATATYPE]);
})

UA_INLINABLE(void UA_ResultValueDataType_clear(UA_ResultValueDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTVALUEDATATYPE]);
})

UA_INLINABLE(void UA_ResultValueDataType_delete(UA_ResultValueDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTVALUEDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_ResultValueDataType_equal(const UA_ResultValueDataType *p1, const UA_ResultValueDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_RESULTVALUEDATATYPE]) == UA_ORDER_EQ);
})

/* SignalDataType: This structure contains the signal information which is used in SetIOSignals and GetIOSignals methods. */
typedef struct {
  UA_String signalId;
  UA_Variant signalValue;
  UA_String signalDescription;
  UA_Int16 signalType;
} UA_SignalDataType;

#define UA_TYPES_IJT_GENERATED_SIGNALDATATYPE 15

UA_INLINABLE(void UA_SignalDataType_init(UA_SignalDataType *p), { memset(p, 0, sizeof(UA_SignalDataType)); })

UA_INLINABLE(UA_SignalDataType *UA_SignalDataType_new(void), {
  return (UA_SignalDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_SIGNALDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_SignalDataType_copy(const UA_SignalDataType *src, UA_SignalDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_SIGNALDATATYPE]);
})

UA_INLINABLE(void UA_SignalDataType_clear(UA_SignalDataType *p), { UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_SIGNALDATATYPE]); })

UA_INLINABLE(void UA_SignalDataType_delete(UA_SignalDataType *p), { UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_SIGNALDATATYPE]); })

UA_INLINABLE(UA_Boolean UA_SignalDataType_equal(const UA_SignalDataType *p1, const UA_SignalDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_SIGNALDATATYPE]) == UA_ORDER_EQ);
})

/* StepResultDataType: This structure represents the measurement values corresponding to a given step in the program. It is used in JoiningResultDataType. */
typedef struct {
  UA_String stepResultId;
  UA_String *programStepId;
  UA_String *programStep;
  UA_String *name;
  UA_ResultEvaluationEnum *resultEvaluation;
  UA_Double *startTimeOffset;
  UA_String *stepTraceId;
  size_t stepResultValuesSize;
  UA_ResultValueDataType *stepResultValues;
} UA_StepResultDataType;

#define UA_TYPES_IJT_GENERATED_STEPRESULTDATATYPE 16

UA_INLINABLE(void UA_StepResultDataType_init(UA_StepResultDataType *p), { memset(p, 0, sizeof(UA_StepResultDataType)); })

UA_INLINABLE(UA_StepResultDataType *UA_StepResultDataType_new(void), {
  return (UA_StepResultDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPRESULTDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_StepResultDataType_copy(const UA_StepResultDataType *src, UA_StepResultDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPRESULTDATATYPE]);
})

UA_INLINABLE(void UA_StepResultDataType_clear(UA_StepResultDataType *p), { UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPRESULTDATATYPE]); })

UA_INLINABLE(void UA_StepResultDataType_delete(UA_StepResultDataType *p), { UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPRESULTDATATYPE]); })

UA_INLINABLE(UA_Boolean UA_StepResultDataType_equal(const UA_StepResultDataType *p1, const UA_StepResultDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPRESULTDATATYPE]) == UA_ORDER_EQ);
})

/* TraceContentDataType: It is to describe of the trace samples for a given program step. It is used in StepTraceDataType. */
typedef struct {
  size_t valuesSize;
  UA_Double *values;
  UA_String *sensorId;
  UA_String *name;
  UA_String *description;
  UA_Byte *physicalQuantity;
  UA_EUInformation *engineeringUnits;
} UA_TraceContentDataType;

#define UA_TYPES_IJT_GENERATED_TRACECONTENTDATATYPE 17

UA_INLINABLE(void UA_TraceContentDataType_init(UA_TraceContentDataType *p), { memset(p, 0, sizeof(UA_TraceContentDataType)); })

UA_INLINABLE(UA_TraceContentDataType *UA_TraceContentDataType_new(void), {
  return (UA_TraceContentDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACECONTENTDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_TraceContentDataType_copy(const UA_TraceContentDataType *src, UA_TraceContentDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACECONTENTDATATYPE]);
})

UA_INLINABLE(void UA_TraceContentDataType_clear(UA_TraceContentDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACECONTENTDATATYPE]);
})

UA_INLINABLE(void UA_TraceContentDataType_delete(UA_TraceContentDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACECONTENTDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_TraceContentDataType_equal(const UA_TraceContentDataType *p1, const UA_TraceContentDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACECONTENTDATATYPE]) == UA_ORDER_EQ);
})

/* TraceDataType: It is a base type to encapsulate common data for a Trace. */
typedef struct {
  UA_String traceId;
  UA_String resultId;
} UA_TraceDataType;

#define UA_TYPES_IJT_GENERATED_TRACEDATATYPE 18

UA_INLINABLE(void UA_TraceDataType_init(UA_TraceDataType *p), { memset(p, 0, sizeof(UA_TraceDataType)); })

UA_INLINABLE(UA_TraceDataType *UA_TraceDataType_new(void), {
  return (UA_TraceDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACEDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_TraceDataType_copy(const UA_TraceDataType *src, UA_TraceDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACEDATATYPE]);
})

UA_INLINABLE(void UA_TraceDataType_clear(UA_TraceDataType *p), { UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACEDATATYPE]); })

UA_INLINABLE(void UA_TraceDataType_delete(UA_TraceDataType *p), { UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACEDATATYPE]); })

UA_INLINABLE(UA_Boolean UA_TraceDataType_equal(const UA_TraceDataType *p1, const UA_TraceDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_TRACEDATATYPE]) == UA_ORDER_EQ);
})

/* StepTraceDataType: It is to describe of the trace for a given program step. It is used in JoiningTraceDataType. */
typedef struct {
  UA_String stepTraceId;
  UA_String stepResultId;
  UA_UInt32 numberOfTracePoints;
  UA_Double *samplingInterval;
  UA_Double *startTimeOffset;
  size_t stepTraceContentSize;
  UA_TraceContentDataType *stepTraceContent;
} UA_StepTraceDataType;

#define UA_TYPES_IJT_GENERATED_STEPTRACEDATATYPE 19

UA_INLINABLE(void UA_StepTraceDataType_init(UA_StepTraceDataType *p), { memset(p, 0, sizeof(UA_StepTraceDataType)); })

UA_INLINABLE(UA_StepTraceDataType *UA_StepTraceDataType_new(void), {
  return (UA_StepTraceDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPTRACEDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_StepTraceDataType_copy(const UA_StepTraceDataType *src, UA_StepTraceDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPTRACEDATATYPE]);
})

UA_INLINABLE(void UA_StepTraceDataType_clear(UA_StepTraceDataType *p), { UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPTRACEDATATYPE]); })

UA_INLINABLE(void UA_StepTraceDataType_delete(UA_StepTraceDataType *p), { UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPTRACEDATATYPE]); })

UA_INLINABLE(UA_Boolean UA_StepTraceDataType_equal(const UA_StepTraceDataType *p1, const UA_StepTraceDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_STEPTRACEDATATYPE]) == UA_ORDER_EQ);
})

/* JoiningTraceDataType: This structure is to describe the content of traces for all the steps in the given program. It is used in JoiningResultDataType. */
typedef struct {
  UA_String traceId;
  UA_String resultId;
  size_t stepTracesSize;
  UA_StepTraceDataType *stepTraces;
} UA_JoiningTraceDataType;

#define UA_TYPES_IJT_GENERATED_JOININGTRACEDATATYPE 20

UA_INLINABLE(void UA_JoiningTraceDataType_init(UA_JoiningTraceDataType *p), { memset(p, 0, sizeof(UA_JoiningTraceDataType)); })

UA_INLINABLE(UA_JoiningTraceDataType *UA_JoiningTraceDataType_new(void), {
  return (UA_JoiningTraceDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGTRACEDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JoiningTraceDataType_copy(const UA_JoiningTraceDataType *src, UA_JoiningTraceDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGTRACEDATATYPE]);
})

UA_INLINABLE(void UA_JoiningTraceDataType_clear(UA_JoiningTraceDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGTRACEDATATYPE]);
})

UA_INLINABLE(void UA_JoiningTraceDataType_delete(UA_JoiningTraceDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGTRACEDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_JoiningTraceDataType_equal(const UA_JoiningTraceDataType *p1, const UA_JoiningTraceDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGTRACEDATATYPE]) == UA_ORDER_EQ);
})

/* JoiningResultDataType: This structure represents the data associated with Joining Result and the corresponding measurement values. */
typedef struct {
  UA_Byte *failureReason;
  size_t overallResultValuesSize;
  UA_ResultValueDataType *overallResultValues;
  size_t stepResultsSize;
  UA_StepResultDataType *stepResults;
  size_t errorsSize;
  UA_ErrorInformationDataType *errors;
  UA_String *failingStepResultId;
  UA_JoiningTraceDataType *trace;
} UA_JoiningResultDataType;

#define UA_TYPES_IJT_GENERATED_JOININGRESULTDATATYPE 21

UA_INLINABLE(void UA_JoiningResultDataType_init(UA_JoiningResultDataType *p), { memset(p, 0, sizeof(UA_JoiningResultDataType)); })

UA_INLINABLE(UA_JoiningResultDataType *UA_JoiningResultDataType_new(void), {
  return (UA_JoiningResultDataType *)UA_new(&UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTDATATYPE]);
})

UA_INLINABLE(UA_StatusCode UA_JoiningResultDataType_copy(const UA_JoiningResultDataType *src, UA_JoiningResultDataType *dst), {
  return UA_copy(src, dst, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTDATATYPE]);
})

UA_INLINABLE(void UA_JoiningResultDataType_clear(UA_JoiningResultDataType *p), {
  UA_clear(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTDATATYPE]);
})

UA_INLINABLE(void UA_JoiningResultDataType_delete(UA_JoiningResultDataType *p), {
  UA_delete(p, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTDATATYPE]);
})

UA_INLINABLE(UA_Boolean UA_JoiningResultDataType_equal(const UA_JoiningResultDataType *p1, const UA_JoiningResultDataType *p2), {
  return (UA_order(p1, p2, &UA_TYPES_IJT_GENERATED[UA_TYPES_IJT_GENERATED_JOININGRESULTDATATYPE]) == UA_ORDER_EQ);
})

_UA_END_DECLS

#endif /* TYPES_IJT_GENERATED_GENERATED_H_ */
