/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef TYPES_GMS_GENERATED_HANDLING_H_
#define TYPES_GMS_GENERATED_HANDLING_H_

#include "types_gms_generated.h"

_UA_BEGIN_DECLS

#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#pragma GCC diagnostic ignored "-Wmissing-braces"
#endif

/* CartesianWorkspaceType */
static UA_INLINE void UA_CartesianWorkspaceType_init(UA_CartesianWorkspaceType *p) { memset(p, 0, sizeof(UA_CartesianWorkspaceType)); }

static UA_INLINE UA_CartesianWorkspaceType *UA_CartesianWorkspaceType_new(void) {
  return (UA_CartesianWorkspaceType *)UA_new(&UA_TYPES_GMS[UA_TYPES_GMS_CARTESIANWORKSPACETYPE]);
}

static UA_INLINE UA_StatusCode UA_CartesianWorkspaceType_copy(const UA_CartesianWorkspaceType *src, UA_CartesianWorkspaceType *dst) {
  return UA_copy(src, dst, &UA_TYPES_GMS[UA_TYPES_GMS_CARTESIANWORKSPACETYPE]);
}

UA_DEPRECATED static UA_INLINE void UA_CartesianWorkspaceType_deleteMembers(UA_CartesianWorkspaceType *p) {
  UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_CARTESIANWORKSPACETYPE]);
}

static UA_INLINE void UA_CartesianWorkspaceType_clear(UA_CartesianWorkspaceType *p) { UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_CARTESIANWORKSPACETYPE]); }

static UA_INLINE void UA_CartesianWorkspaceType_delete(UA_CartesianWorkspaceType *p) { UA_delete(p, &UA_TYPES_GMS[UA_TYPES_GMS_CARTESIANWORKSPACETYPE]); }
static UA_INLINE UA_Boolean UA_CartesianWorkspaceType_equal(const UA_CartesianWorkspaceType *p1, const UA_CartesianWorkspaceType *p2) {
  return (UA_order(p1, p2, &UA_TYPES_GMS[UA_TYPES_GMS_CARTESIANWORKSPACETYPE]) == UA_ORDER_EQ);
}

/* CylindricalWorkspaceType */
static UA_INLINE void UA_CylindricalWorkspaceType_init(UA_CylindricalWorkspaceType *p) { memset(p, 0, sizeof(UA_CylindricalWorkspaceType)); }

static UA_INLINE UA_CylindricalWorkspaceType *UA_CylindricalWorkspaceType_new(void) {
  return (UA_CylindricalWorkspaceType *)UA_new(&UA_TYPES_GMS[UA_TYPES_GMS_CYLINDRICALWORKSPACETYPE]);
}

static UA_INLINE UA_StatusCode UA_CylindricalWorkspaceType_copy(const UA_CylindricalWorkspaceType *src, UA_CylindricalWorkspaceType *dst) {
  return UA_copy(src, dst, &UA_TYPES_GMS[UA_TYPES_GMS_CYLINDRICALWORKSPACETYPE]);
}

UA_DEPRECATED static UA_INLINE void UA_CylindricalWorkspaceType_deleteMembers(UA_CylindricalWorkspaceType *p) {
  UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_CYLINDRICALWORKSPACETYPE]);
}

static UA_INLINE void UA_CylindricalWorkspaceType_clear(UA_CylindricalWorkspaceType *p) { UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_CYLINDRICALWORKSPACETYPE]); }

static UA_INLINE void UA_CylindricalWorkspaceType_delete(UA_CylindricalWorkspaceType *p) { UA_delete(p, &UA_TYPES_GMS[UA_TYPES_GMS_CYLINDRICALWORKSPACETYPE]); }
static UA_INLINE UA_Boolean UA_CylindricalWorkspaceType_equal(const UA_CylindricalWorkspaceType *p1, const UA_CylindricalWorkspaceType *p2) {
  return (UA_order(p1, p2, &UA_TYPES_GMS[UA_TYPES_GMS_CYLINDRICALWORKSPACETYPE]) == UA_ORDER_EQ);
}

/* MeasurementReasonEnum */
static UA_INLINE void UA_MeasurementReasonEnum_init(UA_MeasurementReasonEnum *p) { memset(p, 0, sizeof(UA_MeasurementReasonEnum)); }

static UA_INLINE UA_MeasurementReasonEnum *UA_MeasurementReasonEnum_new(void) {
  return (UA_MeasurementReasonEnum *)UA_new(&UA_TYPES_GMS[UA_TYPES_GMS_MEASUREMENTREASONENUM]);
}

static UA_INLINE UA_StatusCode UA_MeasurementReasonEnum_copy(const UA_MeasurementReasonEnum *src, UA_MeasurementReasonEnum *dst) {
  return UA_copy(src, dst, &UA_TYPES_GMS[UA_TYPES_GMS_MEASUREMENTREASONENUM]);
}

UA_DEPRECATED static UA_INLINE void UA_MeasurementReasonEnum_deleteMembers(UA_MeasurementReasonEnum *p) {
  UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_MEASUREMENTREASONENUM]);
}

static UA_INLINE void UA_MeasurementReasonEnum_clear(UA_MeasurementReasonEnum *p) { UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_MEASUREMENTREASONENUM]); }

static UA_INLINE void UA_MeasurementReasonEnum_delete(UA_MeasurementReasonEnum *p) { UA_delete(p, &UA_TYPES_GMS[UA_TYPES_GMS_MEASUREMENTREASONENUM]); }
static UA_INLINE UA_Boolean UA_MeasurementReasonEnum_equal(const UA_MeasurementReasonEnum *p1, const UA_MeasurementReasonEnum *p2) {
  return (UA_order(p1, p2, &UA_TYPES_GMS[UA_TYPES_GMS_MEASUREMENTREASONENUM]) == UA_ORDER_EQ);
}

/* ToleranceLimitEnum */
static UA_INLINE void UA_ToleranceLimitEnum_init(UA_ToleranceLimitEnum *p) { memset(p, 0, sizeof(UA_ToleranceLimitEnum)); }

static UA_INLINE UA_ToleranceLimitEnum *UA_ToleranceLimitEnum_new(void) {
  return (UA_ToleranceLimitEnum *)UA_new(&UA_TYPES_GMS[UA_TYPES_GMS_TOLERANCELIMITENUM]);
}

static UA_INLINE UA_StatusCode UA_ToleranceLimitEnum_copy(const UA_ToleranceLimitEnum *src, UA_ToleranceLimitEnum *dst) {
  return UA_copy(src, dst, &UA_TYPES_GMS[UA_TYPES_GMS_TOLERANCELIMITENUM]);
}

UA_DEPRECATED static UA_INLINE void UA_ToleranceLimitEnum_deleteMembers(UA_ToleranceLimitEnum *p) {
  UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOLERANCELIMITENUM]);
}

static UA_INLINE void UA_ToleranceLimitEnum_clear(UA_ToleranceLimitEnum *p) { UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOLERANCELIMITENUM]); }

static UA_INLINE void UA_ToleranceLimitEnum_delete(UA_ToleranceLimitEnum *p) { UA_delete(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOLERANCELIMITENUM]); }
static UA_INLINE UA_Boolean UA_ToleranceLimitEnum_equal(const UA_ToleranceLimitEnum *p1, const UA_ToleranceLimitEnum *p2) {
  return (UA_order(p1, p2, &UA_TYPES_GMS[UA_TYPES_GMS_TOLERANCELIMITENUM]) == UA_ORDER_EQ);
}

/* ToolAlignmentState */
static UA_INLINE void UA_ToolAlignmentState_init(UA_ToolAlignmentState *p) { memset(p, 0, sizeof(UA_ToolAlignmentState)); }

static UA_INLINE UA_ToolAlignmentState *UA_ToolAlignmentState_new(void) {
  return (UA_ToolAlignmentState *)UA_new(&UA_TYPES_GMS[UA_TYPES_GMS_TOOLALIGNMENTSTATE]);
}

static UA_INLINE UA_StatusCode UA_ToolAlignmentState_copy(const UA_ToolAlignmentState *src, UA_ToolAlignmentState *dst) {
  return UA_copy(src, dst, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLALIGNMENTSTATE]);
}

UA_DEPRECATED static UA_INLINE void UA_ToolAlignmentState_deleteMembers(UA_ToolAlignmentState *p) {
  UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLALIGNMENTSTATE]);
}

static UA_INLINE void UA_ToolAlignmentState_clear(UA_ToolAlignmentState *p) { UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLALIGNMENTSTATE]); }

static UA_INLINE void UA_ToolAlignmentState_delete(UA_ToolAlignmentState *p) { UA_delete(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLALIGNMENTSTATE]); }
static UA_INLINE UA_Boolean UA_ToolAlignmentState_equal(const UA_ToolAlignmentState *p1, const UA_ToolAlignmentState *p2) {
  return (UA_order(p1, p2, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLALIGNMENTSTATE]) == UA_ORDER_EQ);
}

/* ToolIsQualifiedStatus */
static UA_INLINE void UA_ToolIsQualifiedStatus_init(UA_ToolIsQualifiedStatus *p) { memset(p, 0, sizeof(UA_ToolIsQualifiedStatus)); }

static UA_INLINE UA_ToolIsQualifiedStatus *UA_ToolIsQualifiedStatus_new(void) {
  return (UA_ToolIsQualifiedStatus *)UA_new(&UA_TYPES_GMS[UA_TYPES_GMS_TOOLISQUALIFIEDSTATUS]);
}

static UA_INLINE UA_StatusCode UA_ToolIsQualifiedStatus_copy(const UA_ToolIsQualifiedStatus *src, UA_ToolIsQualifiedStatus *dst) {
  return UA_copy(src, dst, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLISQUALIFIEDSTATUS]);
}

UA_DEPRECATED static UA_INLINE void UA_ToolIsQualifiedStatus_deleteMembers(UA_ToolIsQualifiedStatus *p) {
  UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLISQUALIFIEDSTATUS]);
}

static UA_INLINE void UA_ToolIsQualifiedStatus_clear(UA_ToolIsQualifiedStatus *p) { UA_clear(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLISQUALIFIEDSTATUS]); }

static UA_INLINE void UA_ToolIsQualifiedStatus_delete(UA_ToolIsQualifiedStatus *p) { UA_delete(p, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLISQUALIFIEDSTATUS]); }
static UA_INLINE UA_Boolean UA_ToolIsQualifiedStatus_equal(const UA_ToolIsQualifiedStatus *p1, const UA_ToolIsQualifiedStatus *p2) {
  return (UA_order(p1, p2, &UA_TYPES_GMS[UA_TYPES_GMS_TOOLISQUALIFIEDSTATUS]) == UA_ORDER_EQ);
}

#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
#pragma GCC diagnostic pop
#endif

_UA_END_DECLS

#endif /* TYPES_GMS_GENERATED_HANDLING_H_ */
